In [2]:
!unzip '/content/bank+marketing.zip'

Archive:  /content/bank+marketing.zip
 extracting: bank.zip
 extracting: bank-additional.zip

In [3]:
import pandas as pd

In [4]:
!unzip '/content/bank.zip'

Archive:  /content/bank.zip
  inflating: bank-full.csv
  inflating: bank-names.txt
  inflating: bank.csv

In [5]:
df = pd.read_csv('/content/bank-full.csv', sep=';')

In [6]:
df

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,58,management,married,tertiary,no,2143,yes,no,unknown,5,may,261,1,-1,0,unknown,no
1,44,technician,single,secondary,no,29,yes,no,unknown,5,may,151,1,-1,0,unknown,no
2,33,entrepreneur,married,secondary,no,2,yes,yes,unknown,5,may,76,1,-1,0,unknown,no
3,47,blue-collar,married,unknown,no,1506,yes,no,unknown,5,may,92,1,-1,0,unknown,no
4,33,unknown,single,unknown,no,1,no,no,unknown,5,may,198,1,-1,0,unknown,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45206,51,technician,married,tertiary,no,825,no,no,cellular,17,nov,977,3,-1,0,unknown,yes
45207,71,retired,divorced,primary,no,1729,no,no,cellular,17,nov,456,2,-1,0,unknown,yes
45208,72,retired,married,secondary,no,5715,no,no,cellular,17,nov,1127,5,184,3,success,yes
45209,57,blue-collar,married,secondary,no,668,no,no,telephone,17,nov,508,4,-1,0,unknown,no
45210,37,entrepreneur,married,secondary,no,2971,no,no,cellular,17,nov,361,2,188,11,other,no

In [7]:
df['default'].unique()

array(['no', 'yes'], dtype=object)

#Business Understanding
1. What is the average balance for customers whose job is 'management'?

2. Find the average age for all 'single' customers.

3. For all customers who have a housing loan, what is the count of people in each education level?

4. Among customers with a balance greater than 5000 euros, what is the most common job?

5. For customers who have a personal loan (loan is 'yes'), what is the maximum balance for each marital status?

6. For customers who are 'divorced', what is the average balance for each education level?

7. Among customers whose job is 'technician', what is the average age for each marital status?

8. Find the average balance for customers who have a housing loan but no personal loan.

9. For customers who are 50 years old or older, what is the average balance for each job?

10. For customers who have a housing loan and a personal loan, what is the average age for each marital status?

##### Ave balance for customers whose job is 'management'

In [20]:
ave_balc_management = df[df['job'] == 'management']['balance'].mean()
ave_balc_management

np.float64(1763.6168323112709)

##### Ave age for all 'single' customers

In [22]:
single_ave_age = df[df['marital'] == 'single']['age'].mean()
single_ave_age

np.float64(33.7034401876466)

##### customers who have a housing loan, what is the count of people in each education level

In [9]:
housing_loan_count = df[df['housing'] == 'yes'].groupby('education')['housing'].count()
housing_loan_count.sort_values(ascending=False)

education
secondary    14038
tertiary      6378
primary       3894
unknown        820
Name: housing, dtype: int64

##### cust balance greater than 5000 euros, what is the most common job?

In [10]:
balance_greater_5000 = df[df['balance'] > 5000].groupby('job')['balance'].count()
balance_greater_5000.sort_values(ascending=False)

job
management       872
blue-collar      452
technician       444
admin.           214
retired          200
services         177
self-employed    127
entrepreneur     104
unemployed        95
housemaid         72
student           64
unknown           24
Name: balance, dtype: int64

##### maximum balance for each marital status with loan 'yes'

In [11]:
max_balance_personal_loan = df[df['loan'] == 'yes'].groupby('marital')['balance'].max()
max_balance_personal_loan.sort_values(ascending=False)

marital
married     51439
divorced    24055
single      22125
Name: balance, dtype: int64

##### Ave balance for divorced people for each education level

In [13]:
df.columns

Index(['age', 'job', 'marital', 'education', 'default', 'balance', 'housing',
       'loan', 'contact', 'day', 'month', 'duration', 'campaign', 'pdays',
       'previous', 'poutcome', 'y'],
      dtype='object')

In [14]:
ave_balance_divorced_by_edu_level = df[df['marital'] == 'divorced'].groupby('education')['balance'].mean()
ave_balance_divorced_by_edu_level.sort_values(ascending=False)

education
tertiary     1700.917063
unknown      1417.147929
primary      1137.680851
secondary     902.772647
Name: balance, dtype: float64

##### average balance for customers who have a housing loan but no personal loan

In [15]:
ave_housing_loan_no_personal_loan = df[(df['housing'] == 'yes') & (df['loan'] == 'no')].groupby('marital')['balance'].mean()
ave_housing_loan_no_personal_loan.sort_values(ascending=False)

marital
married     1287.029879
single      1251.651515
divorced    1111.157873
Name: balance, dtype: float64

##### Ave balance for each job of cust aged >=50

In [16]:
ave_50andmore_age_balance = df[df['age'] >= 50].groupby('job')['balance'].mean()

In [17]:
ave_50andmore_age_balance.sort_values(ascending=False)

job
entrepreneur     2302.130790
management       2299.765836
self-employed    2201.504505
retired          2044.979784
unemployed       1841.010000
unknown          1828.130081
admin.           1591.346067
housemaid        1514.759223
blue-collar      1496.072506
technician       1427.492430
services         1376.580442
Name: balance, dtype: float64

##### Ave age by marital status with housing & personal loan

In [18]:
ave_age_by_marital_with_loan = df[(df['housing'] == 'yes') & (df['loan'] == 'yes')].groupby('marital')['age'].mean()
ave_age_by_marital_with_loan.sort_values(ascending=False)

marital
divorced    43.418000
married     40.389431
single      33.531250
Name: age, dtype: float64

In [26]:
df.columns

Index(['age', 'job', 'marital', 'education', 'default', 'balance', 'housing',
       'loan', 'contact', 'day', 'month', 'duration', 'campaign', 'pdays',
       'previous', 'poutcome', 'y'],
      dtype='object')

In [30]:
fav_contact = df[(df['age'] >=20) & (df['age'] <= 50)].groupby('contact')['age'].count()

In [34]:
fav_contact.sort_values(ascending=False)

contact
cellular     23642
unknown      10589
telephone     1678
Name: age, dtype: int64

In [36]:
fav = df['age'].between(20,50)[df['contact']].max()

KeyError: "None of [Index(['unknown', 'unknown', 'unknown', 'unknown', 'unknown', 'unknown',\n       'unknown', 'unknown', 'unknown', 'unknown',\n       ...\n       'cellular', 'cellular', 'cellular', 'cellular', 'cellular', 'cellular',\n       'cellular', 'cellular', 'telephone', 'cellular'],\n      dtype='object', length=45211)] are in the [index]"

In [37]:
df[df['age'].between(20,50)].groupby('contact')['age'].count()

contact
cellular     23642
telephone     1678
unknown      10589
Name: age, dtype: int64

In [46]:
ave_duration = df[(df['contact'] == 'cellular') | (df['contact'] == 'telephone')]['duration'].mean()

In [47]:
ave_duration

np.float64(260.518095119754)

In [38]:
df['contact'].unique()

array(['unknown', 'cellular', 'telephone'], dtype=object)